; Marten — ESP32-S3-Touch-LCD-1.85 Spotify kid player
; https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-1.85

[env:waveshare_s3_1_85]
platform = espressif32 @ ^6.9.0
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
board_build.arduino.memory_type = qio_opi
board_upload.maximum_size = 16777216
build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    -DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM_CACHE_WORKAROUND
    -DSPOTIFY_DEVICE_NAME=\"Marten\ Player\"
    -I${PROJECT_DIR}/include
    -I${PROJECT_DIR}/include/spotify
    -I${PROJECT_DIR}/include/ui
    -I${PROJECT_DIR}/include/board
    -I${PROJECT_DIR}/include/net
    -I${PROJECT_DIR}/components/spotify_connect/include
build_unflags =
    -DBOARD_HAS_PSRAM
board_build.cxxflags =
    -std=gnu++2a
